# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"  # Dependabot revisará las dependencias cada semana
    commit-message:
      prefix: "deps"  # Prefijo para los commits realizados por Dependabot
      include: "scope"  # Incluye el nombre del paquete en el mensaje del commit
    labels:
      - "dependencies"
      - "security"
    # Opcional: Ignores algunas dependencias si no deseas que se actualicen automáticamente
    ignore:
      - dependency-name: "com.fasterxml.jackson.core:jackson-databind"  # Ejemplo de dependencia ignorada
        versions: ["2.10.0"]  # Versión específica a ignorar
